version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
      

  backend:
    build:
      context: ./backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
    command: "rails server -b 0.0.0.0 -p 8080"

