apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app3
  name: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app3
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
